In [1]:
%reset -f

In [2]:
import numpy as np
from PIL import Image

In [3]:
def read_image(image_name,method):
    image = Image.open(image_name)
    image = image.convert(method)
    image_data = np.array(image)
    image_data_row = len(image_data)
    image_data_col = len(image_data[0])
    return (image_data,image_data_row,image_data_col)

Honglu Xu
<br>
EECS531
<br>
HW 1
<br>
Due 02/21/2018

## 2. Edge detector

In this problem, I will use a function in OpenCV. It will detect the edges aautomaticly and return the detected edges as an image.

In [4]:
import cv2
# import matplotlib.pyplot as plt 

I will start from the materials we have, which is the 'charaters.png'.

In [5]:
image_data,_,_ = read_image('characters.png','L')

edges = cv2.Canny(image_data,100,200)

img = Image.fromarray(edges, 'L')
# img.show()
img.save('edge_test1.png')# read the image

<img src='edge_test1.png'>

We can see it worked very well.
<br>
The Canny detector is a very good detector, there is a reference about how it works: https://docs.opencv.org/2.4/doc/tutorials/imgproc/imgtrans/canny_detector/canny_detector.html
<br>
In general, it will firstly use the Gaussian filter, which we have already covered in the problem one, to get away the noise. 
<br>
Then, it will use some edge filters to to detect the edges. The edge filters are similar to the Sobel filter.

In [13]:
G1 = np.array([[-1,0,-1],[-2,0,-2],[1,0,1]])
print("G1:\n",G1)
G2 = np.array([[-1,-2,-1],[0,0,0],[1,2,1]])
print("G2:\n",G2)

G1:
 [[-1  0 -1]
 [-2  0 -2]
 [ 1  0  1]]
G2:
 [[-1 -2 -1]
 [ 0  0  0]
 [ 1  2  1]]


We can see that G1 is for the vertical edge detector, and G2 is for the horizontal edge detector.
<br>
Then, we can use G1 and G2 to calculat the edge direction.
\begin{equation*}
\theta=arctan({\frac{G2}{G1}})
\end{equation*}
And also the gradient
\begin{equation*}
G=\sqrt{G1^2+G2^2}
\end{equation*}
By the document, the direction will be rounded to 0,45,90 or 135.
<br>
After that, it will apply the Non-maximum suppression and use to threasholds to determine whether this edge is the edge that the user wanted.
<br>
They upper threasholds and lower threaholds. The upper threashold is to confirm some obviously edges, and the lower threashold is to pick out some none edge pixels. If the gradient G is between the upper and lower threaholds, it will check whether it is connected to the "obviously edges", if it does, then this will be considered to be edges, too.

<hr>
However, this image only contains the black and white elements, we can try some RGB images that see if that works.
<br>
I found an image from google search.

<img src='forest.jpg'>

Let's turn it to Grayscale iamges so we can apply it to the filter.

In [6]:
image_data,_,_ = read_image('forest.jpg','L')

img = Image.fromarray(image_data, 'L')
img.save('forest_gray.png')

<img src='forest_gray.png'>

Now we can apply the function and see the results.

In [7]:
edges = cv2.Canny(image_data,100,200)

img = Image.fromarray(edges, 'L')
# img.show()
img.save('forest_edge1.png')

<img src='forest_edge1.png'>

We can see this time, it surly covered too many edges. We need to adjust the threshold so only the main edges will be detected.

In [8]:
edges = cv2.Canny(image_data,600,700)

img = Image.fromarray(edges, 'L')
# img.show()
img.save('forest_edge2.png')

<img src='forest_edge2.png'>

After saveral adjustments, I found some thresholds that are reasonable. We can see there are still too many edges that are not the main edges, but we can tell shapes of the elemensts in this image now.